name: CD

on:
  push:
    tags:
      - "*.*.*"

jobs:
  buildAndRelease:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-2019
    name: ${{ matrix.os }}
    env:
      CHILD_CONCURRENCY: "1"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Create Package
        run: yarn package
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts
      - name: Setup Server Package
        run: cp .server.yarnrc .yarnrc
      - name: Clean
        run: git clean -fxd
      - name: Install Dependencies (Server)
        run: yarn --frozen-lockfile
      - name: Create Package (Server)
        run: yarn package
      - name: Create Release (Server)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**
      - name: Upload Artifacts (server)
        uses: actions/upload-artifact@v4
        with:
          name: artifacts (server)
          path: artifacts
