name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-2019
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Create Package
        run: yarn package
      - name: Setup Server Package
        run: cp .server.yarnrc .yarnrc
      - name: Clean
        run: git clean -fxd
      - name: Install Dependencies (Server)
        run: yarn --frozen-lockfile
      - name: Create Package (Server)
        run: yarn package
