name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-2019
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn --frozen-lockfile
          yarn compile
        name: Compile
